$(document).ready(function(){
	//operation input
	$('#percent').on('click',function(element){
		$('#numInput').text('').hide();
		$('#opsInput').text('%').show();
	});
	$('#divide').on('click',function(element){
		$('#numInput').text('').hide();
		$('#opsInput').text('/').show();
	});
	$('#multiply').on('click',function(element){
		$('#numInput').text('').hide();
		$('#opsInput').text('*').show();
	});
	$('#subtract').on('click',function(element){
		$('#numInput').text('').hide();
		$('#opsInput').text('-').show();
	});
	$('#add').on('click',function(element){
		$('#numInput').text('').hide();
		$('#opsInput').text('+').show();
	});
	$('#ce').on('click',function(element){
		$('#numInput').text('').show();
		$('#opsInput').text('').hide();
	});
	$('#ac').on('click',function(element){
		$('#numInput').text('').show();
		$('#opsInput').text('').hide();
		$('#chainOps').text('').hide();
	});
	//number input
	$('#7').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('7').show();
	});
	$('#8').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('8').show();
	});
	$('#9').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('9').show();
	});
	$('#4').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('4').show();
	});
	$('#5').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('5').show();
	});
	$('#6').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('6').show();
	});
	$('#1').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('1').show();
	});
	$('#2').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('2').show();
	});
	$('#3').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('3').show();
	});
	$('#zero-button').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('0').show();
	});
	$('#decimal').on('click',function(element){
		$('#opsInput').hide();
		$('#numInput').append('.').show();
	});
});